<MattGrid>

    GridLayout:
        cols:1
        size: root.width,root.height
        
        GridLayout:
            cols:2
            Label:
                text:"First name: "
            TextInput:
                multiline:False
            Label:
                text:"Email: "
            TextInput:
                multiline:False
        Button:
            text:"Submit"
